- name: configuring frontend
  hosts: frontend
  become: yes
  tasks:
    - name: installing nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: starting service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: removinf directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent 

    - name: creating directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: present

    - name: downloading frontend content
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        dest: /tmp/frontend.zip

    - name: unzip the content 
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
      
    - name: copying config file
      ansible.builtin.copy:
        src: expense.conf 
        dest: /etc/nginx/default.d/expense.conf


    - name: restart the system service
      ansible.builtin.service:
        name: nginx
        state: restarted
