- name: mysql configuration
  hosts: mysql
  become: yes
  vars:
    - mysql_root_password: "ExpenseApp@1"
    - login_host: "mysql.chocojohns.online"
  tasks:

    - name: install mysql dependencies
      ansible.builtin.pip:
        name:
          - PymySQL
        executable: pip3.6

    - name: installing myql server and configuring
      ansible.builtin.package:
        name: mysql-server
        state: present

    - name: starting mysql service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: connect mysql server
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_host: "{{ login_host }}"
      ignore_errors: true
      register: mysql_info

    - name: print the information of mysql
      ansible.builtin.debug:
        msg: "{{ mysql_info }}"
    
    - name: setup MySQL root password
      ansible.builtin.shell: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
      when: mysql_info.failed is true







 